[[mgr.prepend_keymap]]
on  = "y"
run = [ '''
	shell 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list' --confirm
''', "yank" ]


# Open kitty terminal in a new window
[[mgr.prepend_keymap]]
on   = ["T"] # The key
run  = "shell 'kitty' --block=false --orphan=true" # Command to execute
desc = "Open Kitty terminal in new window"

[[mgr.prepend_keymap]]
on = ["C"]
run = "plugin ouch tar.gz"
desc = "Compress with ouch"

[[mgr.prepend_keymap]]
on   = [ "c", "a" ]
run  = "plugin compress"
desc = "Archive selected files"

[[mgr.prepend_keymap]]
on   = [ "z" ]
run  = "plugin zoxide"
desc = "Jump to directory with zoxide"

[[mgr.prepend_keymap]]
on   = [ "Z" ]
run  = "plugin fzf"
desc = "Jump to directory with fzf"
